# // Copyright (c) Microsoft Corporation.
# // Licensed under the MIT license.
{{ if .Values.blue.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment-blue
  labels:
    app: {{ .Values.label.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.label.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.label.name }}
        environment: {{ .Values.environment }}
        slot: blue
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.container.image }}:{{ .Values.blue.tag }}
        imagePullPolicy: {{ .Values.container.pullPolicy }}
        volumeMounts:
        - name: {{ .Release.Name }}-secret
          mountPath: /mnt/keyvault
          readOnly: true
        ports:
          - containerPort: {{ .Values.container.port }}
        env:
          - name: apphost
            value: {{ .Values.apphost }}
          - name: appenvironment
            value: {{ .Values.environment}}
          - name: PostgreSQLControllerConfig__ConnectionStringRoleName
            value: {{ .Values.blue.connectionString.roleName}}
          - name: PostgreSQLControllerConfig__ConnectionStringPwdMountPoint
            value: {{ .Values.blue.connectionString.mountPoint }}
          - name: PostgreSQLControllerConfig__ConnectionStringTemplate
            value: {{ .Values.connectionString.template }}
      imagePullSecrets:
      - name: acrsecret
      volumes:
      - name: {{ .Release.Name }}-secret
        flexVolume:
          driver: "azure/kv"
          options:
            usevmmanagedidentity: "true"
            resourcegroup: {{ .Values.azure.resourceGroupName }}
            keyvaultname: {{ .Values.azure.keyVaultName }}
            keyvaultobjectname: "pgmainbluepwd;pgmaingreenpwd"
            keyvaultobjecttype: secret;secret
            subscriptionid: {{ .Values.azure.subscriptionId }}
            tenantid: {{ .Values.azure.tenantId }}
{{ end }}