# // Copyright (c) Microsoft Corporation.
# // Licensed under the MIT license.
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-stage
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: stage-rotate.contoso.com
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-service-stage
          servicePort: {{ .Values.service.port }}
