# // Copyright (c) Microsoft Corporation.
# // Licensed under the MIT license.
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRo...
kind: Secret
metadata:
  creationTimestamp: null
  name: acrsecret
type: kubernetes.io/dockerconfigjson