# // Copyright (c) Microsoft Corporation.
# // Licensed under the MIT license.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-stage
  labels:
    app: {{ .Values.label.name }}
spec:
  ports:
  - port: {{ .Values.service.port}}
    protocol: TCP
    targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Values.label.name }}
    {{- if eq .Values.productionSlot "pgapproleblue" }}
    slot: green
    {{- else }}
    slot: blue
    {{- end }}
  type: {{ .Values.service.type }}
